export const testFiles2 = [
	'./test/assets/images/test-no-profile-jpg.jpg',
	'./test/assets/images/test-no-profile-tif.tif',
	'./test/assets/images/test-no-profile-webp.webp',
	'./test/assets/images/test-p3-webp.webp',
	'./test/assets/images/test-srgb-avif.avif',
	'./test/assets/images/test-srgb-heic.heic',
]

export const testFiles = [
	'./test/assets/images/test-no-profile-avif.avif',
	'./test/assets/images/test-no-profile-heic.heic',
	'./test/assets/images/test-no-profile-jpg.jpg',
	'./test/assets/images/test-no-profile-png.png',
	'./test/assets/images/test-no-profile-psd.psd',
	'./test/assets/images/test-no-profile-tif.tif',
	'./test/assets/images/test-no-profile-webp.webp',
	'./test/assets/images/test-p3-alpha-png.png',
	'./test/assets/images/test-p3-alpha-psd.psd',
	'./test/assets/images/test-p3-alpha-webp.webp',
	'./test/assets/images/test-p3-avif.avif',
	'./test/assets/images/test-p3-heic.heic',
	'./test/assets/images/test-p3-jpg.jpg',
	'./test/assets/images/test-p3-png.png',
	'./test/assets/images/test-p3-psd.psd',
	'./test/assets/images/test-p3-tif.tif',
	'./test/assets/images/test-p3-webp.webp',
	'./test/assets/images/test-srgb-avif.avif',
	'./test/assets/images/test-srgb-heic.heic',
	'./test/assets/images/test-srgb-jpg.jpg',
	'./test/assets/images/test-srgb-png.png',
	'./test/assets/images/test-srgb-psd.psd',
	'./test/assets/images/test-srgb-tif.tif',
	'./test/assets/images/test-srgb-webp.webp',
]
